/**
 * HMZH TV - THE CTO BUILD
 * Full Stack Logic: TV Nav, Arabic Priority, Social, Voice
 */

// STATE
let channels = [];
let favorites = JSON.parse(localStorage.getItem('hmzh_favs') || '[]');
let sleepTimer = null;
let currentLikes = 0;

document.addEventListener('DOMContentLoaded', () => {
    initApp();
    setupFeatures();
    setupCast();
});

// --- CORE ENGINE ---

async function initApp() {
    try {
        // Fetch Optimized DB (Generated by Python Scraper)
        const res = await fetch('database.json');
        if (!res.ok) throw new Error("Cloud Connectivity Error");
        channels = await res.json();

        console.log(`✅ System Online: ${channels.length} Channels Loaded.`);

        // 1. Setup Hero Section (Top Arab Channel)
        setupHero(channels[0]); // Scraper puts Top Priority first

        // 2. Build Netflix-Style Rows
        buildRows();

    } catch (e) {
        console.error("Critical Failure:", e);
        document.querySelector('.loader-center').innerHTML = "⚠️ فشل الاتصال بالسحابة. يرجى التحديث.";
    }
}

function setupHero(channel) {
    if (!channel) return;
    document.getElementById('hero-title').textContent = channel.name;
    document.getElementById('hero-desc').textContent = channel.description || "بث مباشر حصري على HMZH TV";
    document.getElementById('hero-views').innerHTML = `<i class="fa-solid fa-eye"></i> ${channel.views.toLocaleString()}`;

    // Play button
    document.getElementById('hero-play').onclick = () => playChannel(channel);

    // Dynamic Backdrop (If channel has a good logo, use it blurred, else default)
    // For now using a cool gradient fallback handled in CSS
}

function buildRows() {
    const container = document.getElementById('content-rows');
    container.innerHTML = ''; // Clear loader

    // Helper to create a row
    const createRow = (title, icon, filterFn) => {
        const rowData = channels.filter(filterFn).slice(0, 50); // Limit 50 per row for perf
        if (rowData.length === 0) return;

        const section = document.createElement('section');
        section.className = 'category-row';
        section.innerHTML = `
            <div class="row-title"><i class="${icon}"></i> ${title}</div>
            <div class="row-scroller" id="row-${title}"></div>
        `;

        const scroller = section.querySelector('.row-scroller');

        rowData.forEach(ch => {
            const card = document.createElement('div');
            card.className = 'card';
            card.tabIndex = 0; // Focusable

            card.innerHTML = `
                <img loading="lazy" src="${ch.logo}" onerror="this.src='https://img.icons8.com/3d-fluency/94/tv.png'">
                <div class="card-info">
                    <div style="font-size:12px; font-weight:bold">${ch.name}</div>
                    <div style="font-size:10px; color:#ccc">📺 ${ch.current_program || 'Live'}</div>
                </div>
            `;

            card.onclick = () => playChannel(ch);
            card.onkeydown = (e) => { if (e.key === 'Enter') playChannel(ch); };

            scroller.appendChild(card);
        });

        container.appendChild(section);
    };

    // Define Rows Structure
    createRow('القنوات العربية الرائجة', 'fa-solid fa-fire', c => c.is_arabic);
    createRow('الرياضة (Sports)', 'fa-solid fa-futbol', c => c.category === 'Sports');
    createRow('الأخبار (News)', 'fa-solid fa-newspaper', c => c.category === 'News');
    createRow('الأفلام (Movies)', 'fa-solid fa-film', c => c.category === 'Movies');
    createRow('الأطفال (Kids)', 'fa-solid fa-child', c => c.category === 'Kids');
}

// --- PLAYER SYSTEM ---

function playChannel(ch) {
    const modal = document.getElementById('video-modal');
    modal.classList.remove('hidden');

    document.getElementById('player-title').textContent = ch.name;
    document.getElementById('like-count').textContent = ch.likes || "0";
    currentLikes = ch.likes || 0;

    const video = document.getElementById('video-player');

    if (Hls.isSupported()) {
        const hls = new Hls();
        hls.loadSource(ch.url);
        hls.attachMedia(video);
        hls.on(Hls.Events.MANIFEST_PARSED, () => video.play());
    } else if (video.canPlayType('application/vnd.apple.mpegurl')) {
        video.src = ch.url;
        video.play();
    }

    startAmbilight(video);
}

function closePlayer() {
    document.getElementById('video-modal').classList.add('hidden');
    const video = document.getElementById('video-player');
    video.pause();
    video.src = "";
    stopAmbilight();
}

// --- FEATURES ---

function setupFeatures() {
    // 1. TV Navigation (Arrow Keys)
    document.addEventListener('keydown', (e) => {
        if (['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'].includes(e.key)) {
            // Prevent scrolling page
            e.preventDefault();
            navigateGrid(e.key);
        }

        // 2. Panic Button
        if (e.key === 'Escape') {
            const panic = document.getElementById('panic-overlay');
            if (panic.classList.contains('hidden')) {
                closePlayer();
                panic.classList.remove('hidden');
            } else {
                panic.classList.add('hidden');
            }
        }
    });

    // 3. Voice Control
    const voiceBtn = document.getElementById('voice-btn');
    if ('webkitSpeechRecognition' in window) {
        const recognition = new webkitSpeechRecognition();
        recognition.lang = 'ar-SA';
        voiceBtn.onclick = () => {
            voiceBtn.style.color = '#d63031'; // Recording state
            recognition.start();
        };
        recognition.onresult = (e) => {
            const txt = e.results[0][0].transcript;
            console.log("Voice:", txt);
            document.getElementById('search').value = txt;
            document.getElementById('search').dispatchEvent(new Event('input')); // Trigger search
            voiceBtn.style.color = 'white';
        };
    } else {
        voiceBtn.style.display = 'none';
    }

    // 4. Search Filter
    document.getElementById('search').addEventListener('input', (e) => {
        const term = e.target.value.toLowerCase();
        // Re-render rows with quick filter? 
        // For simplicity in this structure, we might just hide non-matching cards:
        document.querySelectorAll('.card').forEach(card => {
            const name = card.innerText.toLowerCase();
            card.style.display = name.includes(term) ? 'block' : 'none';
        });
    });

    // 5. Sleep Timer
    document.getElementById('sleep-select').addEventListener('change', (e) => {
        clearTimeout(sleepTimer);
        const mins = parseInt(e.target.value);
        if (mins > 0) {
            sleepTimer = setTimeout(() => {
                closePlayer();
                alert("Sleep Timer: Turning off...");
            }, mins * 60 * 1000);
        }
    });
}

// Navigation Logic
function navigateGrid(key) {
    const focusable = Array.from(document.querySelectorAll('.card, button, input'));
    const current = document.activeElement;
    let idx = focusable.indexOf(current);

    if (idx === -1) {
        focusable[0].focus();
        return;
    }

    // Simple directional logic (Linear for now, but efficient)
    if (key === 'ArrowRight' || key === 'ArrowDown') idx++;
    if (key === 'ArrowLeft' || key === 'ArrowUp') idx--;

    if (idx >= 0 && idx < focusable.length) {
        focusable[idx].focus();
        focusable[idx].scrollIntoView({ behavior: 'smooth', block: 'center' });
    }
}

// Ambilight FX
let ambiInterval;
function startAmbilight(video) {
    const canvas = document.getElementById('ambilight');
    const ctx = canvas.getContext('2d');
    ambiInterval = setInterval(() => {
        if (!video.paused && !video.ended) {
            ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
        }
    }, 100);
}
function stopAmbilight() {
    clearInterval(ambiInterval);
}

function addLike() {
    currentLikes++;
    document.getElementById('like-count').textContent = currentLikes;
    // Save to local storage logic here
}

function setupCast() {
    window['__onGCastApiAvailable'] = function (isAvailable) {
        if (isAvailable) {
            cast.framework.CastContext.getInstance().setOptions({
                receiverApplicationId: chrome.cast.media.DEFAULT_MEDIA_RECEIVER_APP_ID,
                autoJoinPolicy: chrome.cast.AutoJoinPolicy.ORIGIN_SCOPED
            });
        }
    };
}
