// HMZH TV Cloud - Main App

let allChannels = [];

document.addEventListener('DOMContentLoaded', () => {
    loadDB();

    document.getElementById('search').addEventListener('input', (e) => {
        const q = e.target.value.toLowerCase();
        render(allChannels.filter(c => c.name.toLowerCase().includes(q)));
    });
});

async function loadDB() {
    const grid = document.getElementById('grid');
    try {
        // In GitHub Pages, this file is generated by the Action
        const res = await fetch('database.json');
        if (!res.ok) throw new Error("DB not found");
        allChannels = await res.json();
        render(allChannels);
    } catch (e) {
        console.error(e);
        grid.innerHTML = '<div style="color:white; padding:20px">No Database Found. Please wait for the GitHub Action to run.</div>';
    }
}

function render(list) {
    const grid = document.getElementById('grid');
    grid.innerHTML = '';

    list.slice(0, 100).forEach(ch => {
        const el = document.createElement('div');
        el.className = 'card';
        // Accessibility for TV Remote
        el.tabIndex = 0;

        el.innerHTML = `
            <img src="${ch.logo}" onerror="this.src='https://img.icons8.com/fluency/96/tv.png'">
            <div class="title">${ch.name}</div>
        `;

        el.onclick = () => play(ch);
        // Enter key for TV remote
        el.onkeydown = (e) => { if (e.key === 'Enter') play(ch); };

        grid.appendChild(el);
    });
}

function filter(cat) {
    const btns = document.querySelectorAll('.cat-btn');
    btns.forEach(b => b.classList.remove('active'));
    event.target.classList.add('active'); // event is global in inline onclick (simplified)

    if (cat === 'All') render(allChannels);
    else render(allChannels.filter(c => c.category === cat));
}

function play(ch) {
    const container = document.getElementById('player-container');
    const video = document.getElementById('video');
    const title = document.getElementById('channel-name');

    container.classList.remove('hidden');
    title.textContent = ch.name;
    video.scrollIntoView();

    if (Hls.isSupported()) {
        const hls = new Hls();
        hls.loadSource(ch.url);
        hls.attachMedia(video);
        hls.on(Hls.Events.MANIFEST_PARSED, () => video.play());
    } else if (video.canPlayType('application/vnd.apple.mpegurl')) {
        video.src = ch.url;
        video.play();
    }

    // Attempt casting if session active
    // const session = cast.framework.CastContext.getInstance().getCurrentSession();
    // if(session) castStream(ch.url, 'application/x-mpegurl', ch.name, ch.logo);
}

function closePlayer() {
    const container = document.getElementById('player-container');
    const video = document.getElementById('video');
    container.classList.add('hidden');
    video.pause();
    video.src = "";
}
